// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransitTrackerWebApi.Repositories;

#nullable disable

namespace TransitTrackerWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251226152032_AddRegionsAndFeeds")]
    partial class AddRegionsAndFeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransitTrackerWebApi.Models.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyUrl")
                        .HasColumnType("text")
                        .HasColumnName("agency_url");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_feeds");

                    b.HasIndex("RegionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_feeds_region_id_name");

                    b.ToTable("feeds", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("MaxLat")
                        .HasColumnType("double precision")
                        .HasColumnName("max_lat");

                    b.Property<double?>("MaxLon")
                        .HasColumnType("double precision")
                        .HasColumnName("max_lon");

                    b.Property<double?>("MinLat")
                        .HasColumnType("double precision")
                        .HasColumnName("min_lat");

                    b.Property<double?>("MinLon")
                        .HasColumnType("double precision")
                        .HasColumnName("min_lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.HasIndex("CountryCode", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_regions_country_code_name");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer")
                        .HasColumnName("agency_id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int>("FeedId")
                        .HasColumnType("integer")
                        .HasColumnName("feed_id");

                    b.Property<string>("GtfsRouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gtfs_route_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LongName")
                        .HasColumnType("text")
                        .HasColumnName("long_name");

                    b.Property<int>("RouteType")
                        .HasColumnType("integer")
                        .HasColumnName("route_type");

                    b.Property<int?>("ScopeOverride")
                        .HasColumnType("integer")
                        .HasColumnName("scope_override");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("TextColor")
                        .HasColumnType("text")
                        .HasColumnName("text_color");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_routes_agency_id");

                    b.HasIndex("FeedId")
                        .HasDatabaseName("ix_routes_feed_id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.RouteShape", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id")
                        .HasColumnOrder(0);

                    b.Property<string>("GtfsShapeId")
                        .HasColumnType("text")
                        .HasColumnName("gtfs_shape_id")
                        .HasColumnOrder(1);

                    b.HasKey("RouteId", "GtfsShapeId")
                        .HasName("pk_route_shapes");

                    b.ToTable("route_shapes", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Geom")
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("geom");

                    b.Property<string>("GtfsShapeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gtfs_shape_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_shapes");

                    b.ToTable("shapes", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.ShapeLine", b =>
                {
                    b.Property<string>("GtfsShapeId")
                        .HasColumnType("text")
                        .HasColumnName("gtfs_shape_id");

                    b.Property<LineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (LineString, 4326)")
                        .HasColumnName("geom");

                    b.HasKey("GtfsShapeId")
                        .HasName("pk_shape_lines");

                    b.ToTable("shape_lines", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AchievementId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("achievement_id");

                    b.Property<int?>("ProgressAtUnlock")
                        .HasColumnType("integer")
                        .HasColumnName("progress_at_unlock");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_achievements");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_achievements_user_id_achievement_id");

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.UserAuthProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_auth_providers");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_auth_providers_provider_provider_user_id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_user_auth_providers_user_id_provider");

                    b.ToTable("user_auth_providers", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.UserRouteProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_route_progress");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_user_route_progress_route_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_route_progress_user_id");

                    b.ToTable("user_route_progress", (string)null);
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.Feed", b =>
                {
                    b.HasOne("TransitTrackerWebApi.Models.Region", "Region")
                        .WithMany("Feeds")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feeds_regions_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.Route", b =>
                {
                    b.HasOne("TransitTrackerWebApi.Models.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routes_agencies_agency_id");

                    b.HasOne("TransitTrackerWebApi.Models.Feed", "Feed")
                        .WithMany("Routes")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routes_feeds_feed_id");

                    b.Navigation("Agency");

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.UserAchievement", b =>
                {
                    b.HasOne("TransitTrackerWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.UserAuthProvider", b =>
                {
                    b.HasOne("TransitTrackerWebApi.Models.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_auth_providers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.UserRouteProgress", b =>
                {
                    b.HasOne("TransitTrackerWebApi.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_route_progress_routes_route_id");

                    b.HasOne("TransitTrackerWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_route_progress_users_user_id");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.Feed", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.Region", b =>
                {
                    b.Navigation("Feeds");
                });

            modelBuilder.Entity("TransitTrackerWebApi.Models.User", b =>
                {
                    b.Navigation("AuthProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
